# Generated by Django 4.2.23 on 2025-09-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('dept', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('doj', models.CharField(max_length=10)),
            ],
        ),
    ]
