# Generated by Django 4.2.23 on 2025-09-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
